### ISSUE TITLE
Run a static analysis tool

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#1]
We have to run a static analysis tool on the code.

**Comment by vpeter93** [comment]
With SonarQube https://github.com/pmmp-iet/neo4j-drivers/wiki/Static-analysis-with-SonarQube
and FindBugs https://github.com/pmmp-iet/neo4j-drivers/wiki/Static-analysis-with-FindBugs-Eclipse-plugin

**Comment by kocsipetra** [comment]
seen in documentation, ok

**Comment by milangfx** [comment]
Ok.

**Comment by micskeiz** [comment]
OK
