### ISSUE TITLE
Annotate the "ReactiveDriver" interface with the @FunctionalInterface annotation  in neo4j-drivers neo4j-reactive-driver-interfaces src/.../driver/reactive/interfaces/ReactiveDriver.java 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#10]
Annotate the "ReactiveDriver" interface with the @FunctionalInterface annotation  in neo4j-drivers neo4j-reactive-driver-interfaces src/.../driver/reactive/interfaces/ReactiveDriver.java

**Comment by kocsipetra** [comment]
ok, added @FunctionalInterface annotation

**Comment by milangfx** [comment]
Ok.
