### ISSUE TITLE
Add a private constructor to hide the implicit public one in neo4j-drivers neo4j-driver-util src/main/java/neo4j/driver/util/PrettyPrinter.java 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#11]
Add a private constructor to hide the implicit public one in neo4j-drivers neo4j-driver-util src/main/java/neo4j/driver/util/PrettyPrinter.java in line

**Comment by kocsipetra** [comment]
ok, added private constructor

**Comment by milangfx** [comment]
Ok.
