### ISSUE TITLE
Return an empty collection instead of null in neo4j-drivers neo4j-embedded-testkit-driver src/.../java/neo4j/driver/testkit/data/EmbeddedTestkitStatementResult.java 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#12]
Return an empty collection instead of null in neo4j-drivers neo4j-embedded-testkit-driver src/.../java/neo4j/driver/testkit/data/EmbeddedTestkitStatementResult.java in line 63

**Comment by kocsipetra** [comment]
ok, returns collection instead of null

**Comment by milangfx** [comment]
Ok.
