### ISSUE TITLE
1 duplicated blocks of code must be removed in  src/.../java/neo4j/driver/transactions/SessionDependentTransaction.java

### ISSUE THREAD

**Issue by kocsipetra** [pmmp-iet/neo4j-drivers#19]

**Comment by milangfx** [comment]
Ok.

**Comment by vpeter93** [comment]
We can't fix it, because we can't change org.neo4j.driver.v1.Transaction interface.

**Comment by vpeter93** [comment]
neo4j-driver-common\src\main\java\neo4j\driver\transactions\SessionDependentTransaction.java in StatementResult run(String statementTemplate, Value parameters) and public StatementResult run(String statementTemplate, Record statementParameters) methods. Value and Record extends MapAccessorWithDefaultValue.

**Comment by vpeter93** [comment]
http://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/v1/Record.html
http://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/v1/Value.html
