### ISSUE TITLE
Repair the infinite recursion in neo4j-reactive-driver-impl neo4j.driver.impl.Neo4jReactiveSession

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#2]
public Transaction beginTransaction(String bookmark) in neo4j-reactive-driver-impl neo4j.driver.impl.Neo4jReactiveSession line 125

**Comment by vpeter93** [comment]
Repaired:
https://github.com/pmmp-iet/neo4j-drivers/commit/b03d1267692d02d0969eab311abd0f7d161159e5

**Comment by vpeter93** [comment]
https://github.com/pmmp-iet/neo4j-drivers/commit/ee603bfeb43a24ca6095e473eaa39bbb3736e127

**Comment by kocsipetra** [comment]
Ok, repaired with the right method call

**Comment by milangfx** [comment]
Ok.
