### ISSUE TITLE
Remove depricated code from  src/.../neo4j/driver/reactive/impl/Neo4jReactiveSession.java

### ISSUE THREAD

**Issue by kocsipetra** [pmmp-iet/neo4j-drivers#21]

**Comment by vpeter93** [comment]
This is not a problem. It is just an Info in SonarQube. Theese Infos are caused by solution of #5 and #9 issues. We shouldn't remove deprecated methods. We must implement all methods from the interface.

**Comment by milangfx** [comment]
Ok.
