### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#22]
We want to run an Eclipse in docker with this project.

**Comment by vpeter93** [comment]
https://github.com/pmmp-iet/neo4j-drivers/commit/6bcb7395e7f9a4225ff8140122f98fa47f0c5074
Added Docker support to Ubuntu based distros.

**Comment by vpeter93** [comment]
I try this on Windows.

**Comment by vpeter93** [comment]
https://github.com/pmmp-iet/neo4j-drivers/wiki/How-to-deploy-the-neo4j-to-Docker This is my documentation.

**Comment by vpeter93** [comment]
I can't use Docker with GUI in Windows.

**Comment by milangfx** [comment]
Seen in documentation, ok.

**Comment by kocsipetra** [comment]
Checked ducumentation, nice work.

**Comment by micskeiz** [comment]
OK
