### ISSUE TITLE
Add code coverage test with jacoco

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#24]
I want to add jacoco support to the project. I am going to use jacoco gradle plugin.

**Comment by vpeter93** [comment]
This is my documentation https://github.com/pmmp-iet/neo4j-drivers/wiki/Code-coverage-test-with-Jacoco

**Comment by kocsipetra** [comment]
Ok, checked it, it is correct

**Comment by milangfx** [comment]
Ok
