### ISSUE TITLE
 neo4j-reactive-driver-interfaces  src/.../java/neo4j/driver/reactive/data/ChangeSet.java

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#3]
neo4j-reactive-driver-interfaces src/.../java/neo4j/driver/reactive/data/ChangeSet.java line 28
This is SonarQubes's recommendation:
%n should be used in place of \n to produce the platform-specific line separator.

**Comment by kocsipetra** [comment]
Ok, %n replaced with \n

**Comment by T00pi** [comment]
Seems ok to me.
\n replaced with %n (platform-specific new line)

**Comment by milangfx** [comment]
Ok.
