### ISSUE TITLE
Create test to neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitStatementResult public Record peek() 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#36]
neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitStatementResult line 48

**Comment by vpeter93** [comment]
This is a "throw UnsupportedException" primitve implementation. I won't create test to it.

**Comment by milangfx** [comment]
Ok.
