### ISSUE TITLE
Create test to neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitStatementResult public <T> List<T> list(Function<Record, T>mapFunction) 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#38]
neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitStatementResult line 62

**Comment by vpeter93** [comment]
This is a "return Collections.emptyList();" primitve implementation. I won't create a test to it.

**Comment by milangfx** [comment]
Ok.
