### ISSUE TITLE
Create test to neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitStatementResult public ResultSummary consume()

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#39]
neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitStatementResult line 67

**Comment by vpeter93** [comment]
This is "return null" primitve implementation. I won't create test to this.

**Comment by milangfx** [comment]
Ok
