### ISSUE TITLE
neo4j-reactive-driver-impl src/.../neo4j/driver/reactive/impl/Neo4jRecordChangeSetListener.java

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#4]
neo4j-reactive-driver-impl src/.../neo4j/driver/reactive/impl/Neo4jRecordChangeSetListener.java line 16
SonarQube's recommendation:
Replace this usage of System.out or System.err by a logger. 
When logging a message there are several important requirements which must be fulfilled:

    The user must be able to easily retrieve the logs
    The format of all logged message must be uniform to allow the user to easily read the log
    Logged data must actually be recorded
    Sensitive data must only be logged securely

If a program directly writes to the standard outputs, there is absolutely no way to comply with those requirements. That's why defining and using a dedicated logger is highly recommended.
Noncompliant Code Example

System.out.println("My Message");  // Noncompliant

Compliant Solution

logger.log("My Message");

**Comment by vpeter93** [comment]
This commit cause two other bugs:
Use the built-in formatting to construct this argument.  in line 19
Invoke method(s) only conditionally.  in line 20

**Comment by vpeter93** [comment]
Reorder the modifiers to comply with the Java Language Specification.  in line 10

**Comment by kocsipetra** [comment]
Ok, changed the system.outs

**Comment by milangfx** [comment]
Ok.
