### ISSUE TITLE
Create test to neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitSession public Transaction beginTransaction(Srting bookmark) 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#46]
neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitSession line 79

**Comment by vpeter93** [comment]
This is a TestKit class with primitive implementation. We don't need test to a this method.

**Comment by milangfx** [comment]
Ok
