### ISSUE TITLE
Create test to neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitSession public String lastBookmark 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#47]
neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitSession line 84

**Comment by vpeter93** [comment]
This is a TestKit class with primitive implementation. We don't need test to a TestKit class.

**Comment by vpeter93** [comment]
This is a TestKit class with primitive implementation. We don't need test to a this method.

**Comment by milangfx** [comment]
Ok
