### ISSUE TITLE
Create test to neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitDriver public Session session(String bookmark) 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#54]
neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitDriver line 52

**Comment by vpeter93** [comment]
This is a TestKit class with primitive implementation. We don't need test to a TestKit class.

**Comment by vpeter93** [comment]
This a "throw UnsupportedOperationException" primitve implementation. I won't create test to it.

**Comment by milangfx** [comment]
Ok
