### ISSUE TITLE
Create test to neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitDriver public Session session(AccesMode mode, String bookmark) 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#55]
neo4j-embedded-testkit-driver\src\main\java\neo4j\driver\testkit\EmbeddedTestkitDriver line 57

**Comment by vpeter93** [comment]
This is a TestKit class with primitive implementation. We don't need test to a TestKit class.

**Comment by vpeter93** [comment]
This a "throw UnsupportedOperationException" primitve implementation. I won't create test to it.

**Comment by T00pi** [comment]
Maybe one simple is useful as a reminder, in case it changes in the future
