### ISSUE TITLE
Create test to neo4j-reactive-driver-impl\src\main\java\neo4j\driver\reactive\impl\Neo4jReactiveSession run(String) 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#64]
neo4j-reactive-driver-impl\src\main\java\neo4j\driver\reactive\impl\Neo4jReactiveSession line 103

**Comment by vpeter93** [comment]
OK

**Comment by vpeter93** [comment]
OK, fixed it

**Comment by T00pi** [comment]
The code seem's fine, but the second commit not solved that

**Comment by vpeter93** [comment]
You are right! This commit solved that:
https://github.com/pmmp-iet/neo4j-drivers/commit/2e5e51115741a7b5c6b77e1bb26ec9752c00a86c

**Comment by T00pi** [comment]
Yeah

**Comment by milangfx** [comment]
Assert added, ok.
