### ISSUE TITLE
 Create test to neo4j-reactive-driver-impl\src\main\java\neo4j\driver\reactive\impl\Neo4jReactiveSession typeSystem() 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#69]
neo4j-reactive-driver-impl\src\main\java\neo4j\driver\reactive\impl\Neo4jReactiveSession line 113

**Comment by vpeter93** [comment]
This is a TestKit class with primitive implementation. We don't need test to a this method.

**Comment by vpeter93** [comment]
typeSystem is not supported, I can't test it

**Comment by T00pi** [comment]
Indeed. The typeSystem() function in EmbeddedTestkitSession.java throws UnsupportedOperationException exception.
