### ISSUE TITLE
Replace lambda in neo4j-drivers neo4j-embedded-testkit-driver src/.../java/neo4j/driver/testkit/data/EmbeddedTestkitRecordFactory.java 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#7]
Replace this lambda with a method reference  in neo4j-drivers neo4j-embedded-testkit-driver src/.../java/neo4j/driver/testkit/data/EmbeddedTestkitRecordFactory.java line 72

**Comment by milangfx** [comment]
Ok.

**Comment by kocsipetra** [comment]
Tried to solve it, but dont think it is possible to replace "?" with method reference
