### ISSUE TITLE
Create test to neo4j-reactive-driver-impl\src\main\java\neo4j\driver\reactive\impl\Neo4jReactiveSession lastBookmark() 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#70]
neo4j-reactive-driver-impl\src\main\java\neo4j\driver\reactive\impl\Neo4jReactiveSession line 132

**Comment by kocsipetra** [comment]
checked it, the session.lastBookmark() method wont be called, because EmbeddedTestkitDriver doesnt support it

**Comment by T00pi** [comment]
To be more specific, it will be called but it doesn't exist
