### ISSUE TITLE
 Create test to neo4j-reactive-driver-impl\src\main\java\neo4j\driver\reactive\impl\Neo4jReactiveSession reset() 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#71]
neo4j-reactive-driver-impl\src\main\java\neo4j\driver\reactive\impl\Neo4jReactiveSession line 139

**Comment by kocsipetra** [comment]
it is a deprecated method, we dont want to test it

**Comment by vpeter93** [comment]
I agree with you

**Comment by milangfx** [comment]
Ok
