### ISSUE TITLE
Add JUnit tests to increase tests code coverage

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#75]
We want to create new JUnit tests to solve #25-#74 issues

**Comment by vpeter93** [comment]
We are going to create documentation to this wiki page:
https://github.com/pmmp-iet/neo4j-drivers/wiki/Add-JUnit-tests-to-increase-code-coverage

**Comment by vpeter93** [comment]
It is ready

**Comment by milangfx** [comment]
Ok
