### ISSUE TITLE
Deprecated reset method use in neo4j-drivers neo4j-reactive-driver-impl src/.../neo4j/driver/reactive/impl/Neo4jReactiveSession.java 

### ISSUE THREAD

**Issue by vpeter93** [pmmp-iet/neo4j-drivers#9]
Remove this use of "reset"; it is deprecated in neo4j-drivers neo4j-reactive-driver-impl src/.../neo4j/driver/reactive/impl/Neo4jReactiveSession.java line 139

**Comment by kocsipetra** [comment]
ok, added deprecated annotation

**Comment by milangfx** [comment]
Ok.
